package com.kisaragieffective.opencommandblock.command

import org.bukkit.command.ConsoleCommandSender

interface ConsoleCommandListener : com.kisaragieffective.opencommandblock.command.LCommandExecutor<ConsoleCommandSender>