package com.github.kisaragieffective.opencommandblock.api.wrapper.plugin

import com.github.kisaragieffective.opencommandblock.annotations.DependencyInjection

@DependencyInjection
interface LoggingPluginWrapper : JavaPluginWrapper